version: '3.0'
services:

  website:
    build: ./frontend
    restart: always
    ports:
      - "10000:80"
    links:
      - api-server
    depends_on:
      - api-server
    network_mode: bridge
    command: ['nginx', '-g', 'daemon off;']

  mobile-website:
    build: ./mobile
    restart: always
    ports:
      - "10001:80"
    links:
      - api-server
    depends_on:
      - api-server
    network_mode: bridge
    command: ['nginx', '-g', 'daemon off;']
      
  api-server:
    build: ./api-server
    restart: always
    network_mode: bridge
