version: '3.0'
services:

  cailab-homepage-frontend:
    container_name: cailab-homepage-frontend-vm1
    image: cailab-homepage-frontend-vm1
    ports:
      - "10000:80"
    build: ./frontend
    restart: always
    depends_on:
      - cailab-homepage-api
    networks:
      webservice:
        aliases:
          - cailab-homepage-frontend
    command: ['nginx', '-g', 'daemon off;']

  cailab-homepage-mobile:
    container_name: cailab-homepage-mobile-vm1
    image: cailab-homepage-mobile-vm1
    ports:
      - "10001:80"
    build: ./mobile
    restart: always
    depends_on:
      - cailab-homepage-api
    networks:
      webservice:
        aliases:
          - cailab-homepage-mobile
    command: ['nginx', '-g', 'daemon off;']

  cailab-homepage-api:
    container_name: cailab-homepage-api-vm1
    image: cailab-homepage-api-vm1
    build: ./api-server
    restart: always
    networks:
      webservice:
        aliases:
          - cailab-homepage-api
          - api-server

networks:
  webservice:
    driver: bridge

